### PR TITLE
Windows backend

### LINKED ISSUE #1: Windows backend implementation

### PR DESCRIPTION
**Pull request by ForNeVeR**
Close #1.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
@gsomix wanna review?

**Comment by gsomix** [comment]
With great pleasure!

**Review by gsomix — APPROVED** [review]
OK, it was challenging, but interesting. 

LGTM. Thanks!

**Comment by ForNeVeR** [comment]
Thanks for the review!

**Pull request merged**
